
name: CI with Changed Areas

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.changes.outputs.backend_changed }}
      frontend_changed: ${{ steps.changes.outputs.frontend_changed }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Detect changed areas
        id: changes
        uses: f1rmtea/changed-files@v1
        with:
          config: .github/changed-areas.yml

  test-backend:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run backend tests
        run: npm test -- --testPathPattern=backend

  test-frontend:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run frontend tests
        run: npm test -- --testPathPattern=frontend