name: Monorepo CI

on: [push, pull_request]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      areas: ${{ steps.changes.outputs.areas_json }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Detect changes
        id: changes
        uses: your-org/changed-areas-action@v1

  test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        area: [backend, frontend, api, workers]
    steps:
      - uses: actions/checkout@v4
      
      - name: Check if area changed
        id: check
        run: |
          AREAS='${{ needs.detect-changes.outputs.areas }}'
          CHANGED=$(echo $AREAS | jq -r '."${{ matrix.area }}".changed')
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT
      
      - name: Run tests for ${{ matrix.area }}
        if: steps.check.outputs.changed == 'true'
        run: npm run test:${{ matrix.area }}